version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: wordpress_db
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - wordpress_network
    volumes:
      - db_data:/home/admin/mysql

  wordpress:
    image: wordpress:latest
    container_name: wordpress_app
    depends_on: 
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wordpress_network
    volumes:
      - wordpress_data:/home/admin/wordpress

networks:
    wordpress_network:
      name: wordnet


volumes:
  db_data:
  wordpress_data:

